services:
  mysql:
    image: mysql:8.0
    container_name: mysql_container_minha_prata
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: senha123
      MYSQL_DATABASE: MINHA_PRATA
      MYSQL_USER: admin
      MYSQL_PASSWORD: senha123
    ports:
      - "3336:3306"
