services:
  mysql:
    image: mysql:8.0
    container_name: mysql_container_minha_prata
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: senha123
      MYSQL_DATABASE: MINHA_PRATA
      MYSQL_USER: admin
      MYSQL_PASSWORD: senha123
    ports:
      - "3336:3306"
    volumes:
      - mysql_data_container:/data/mysql

  redis:
    image: redis:4
    container_name: redis_container_minha_prata
    restart: always
    ports:
      - "6380:6380"
    volumes:
      - redis_data_container:/data/redis

  zookeeper:
    image: confluentinc/cp-zookeeper:7.5.0
    container_name: zookeeper_container_minha_prata
    restart: always
    ports:
      - "2181:2181"
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    volumes:
      - zookeeper_data_container:/var/lib/zookeeper

  kafka:
    image: confluentinc/cp-kafka:7.5.0
    container_name: kafka_container_minha_prata
    restart: always
    ports:
      - "9092:9092"
    depends_on:
      - zookeeper
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    volumes:
      - kafka_data_container:/var/lib/kafka/data

volumes:
  mysql_data_container:
  redis_data_container:
  zookeeper_data_container:
  kafka_data_container: